/**
 * Bot command definitions (for the Telegram command menu) and help text.
 */
export const COMMANDS: { command: string; description: string }[] = [
  { command: "start", description: "Welcome, menu & status panel" },
  { command: "menu", description: "Show the menu keyboard" },
  { command: "projects", description: "Projects: list / search <q> / open <path> / new <name>" },
  { command: "sessions", description: "List/resume sessions (active first) \u00b7 /sessions <q>" },
  { command: "active", description: "Sessions running now on the PC" },
  { command: "running", description: "Sessions this chat controls \u2014 switch between them" },
  { command: "killall", description: "Kill all active sessions on the PC" },
  { command: "mcp", description: "Inspect & toggle MCP servers \u00b7 health-check" },
  { command: "tasks", description: "Manage scheduled tasks" },
  { command: "newtask", description: "Create a scheduled task" },
  { command: "history", description: "Show recent conversation history" },
  { command: "new", description: "Start a fresh session here" },
  { command: "status", description: "Current session, project & queue" },
  { command: "usage", description: "Provider & context usage" },
  { command: "connect", description: "Connect a provider: /connect <provider> <api-key>" },
  { command: "models", description: "Browse & select models" },
  { command: "btw", description: "Run ASAP (now if idle, else next): /btw <text>" },
  { command: "flush", description: "Send queued follow-ups now" },
  { command: "queue", description: "Show queued follow-ups" },
  { command: "cancel", description: "Stop the current turn" },
  { command: "unwatch", description: "Stop following a live session" },
  { command: "model", description: "Switch model: /model <id>" },
  { command: "restart", description: "Restart the OpenCode agent" },
  { command: "help", description: "Show help" },
];

export const HELP_TEXT = [
  "\u{1F916} OpenCode Telegram Bot",
  "Drive OpenCode from your phone \u2014 projects, resume, live sessions, diffs.",
  "",
  "HOW IT WORKS",
  "\u2022 Just send a message to chat with OpenCode in the current project.",
  "\u2022 While OpenCode is working, anything you send is queued and runs",
  "  automatically when the current turn finishes.",
  "",
  "COMMANDS",
  "/projects \u2014 choose which folder OpenCode works in",
  "/sessions \u2014 resume one of your recent OpenCode sessions",
  "/active \u2014 attach to a session currently running on the PC",
  "/history \u2014 show the latest messages of the current session",
  "/new \u2014 start a brand-new session in the current project",
  "/btw <text> \u2014 run it now if idle, otherwise right after the current task",
  "/flush \u2014 run queued follow-ups immediately",
  "/cancel \u2014 stop the current turn",
  "/status \u2014 show session, project and queue size",
].join("\n");
